name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: apt-get update && apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: postgres
          DB_PORT: 5432
        run: |
          until pg_isready -h postgres -p 5432 -U "$DB_USER"; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

          # Using PGPASSWORD to securely pass the password
          PGPASSWORD=$DB_PASSWORD psql -h postgres -U "$DB_USER" -c "CREATE DATABASE \"$DB_NAME\";"
          PGPASSWORD=$DB_PASSWORD psql -h postgres -U "$DB_USER" -c "CREATE ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD';"
          PGPASSWORD=$DB_PASSWORD psql -h postgres -U "$DB_USER" -c "GRANT ALL PRIVILEGES ON DATABASE \"$DB_NAME\" TO \"$DB_USER\";"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: postgres # Refers to the postgres service
          DB_PORT: 5432
        run: npm test

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
