name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: node:latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: webapp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: apt-get update && apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "$DB_USER"
          echo "$DB_PASSWORD"
          echo "$DB_NAME"
          until pg_isready -h postgres -p 5432 -U "$DB_USER"; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

          if [ -z "$DB_NAME" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
            echo "One or more required environment variables are not set."
            exit 1
          fi

          psql -h postgres -U postgres -c "CREATE DATABASE \"$DB_NAME\";"
          psql -h postgres -U postgres -c "CREATE ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD';"
          psql -h postgres -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE \"$DB_NAME\" TO \"$DB_USER\";"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: postgres # Use the service name
        run: npm test

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

  packer-check:
    needs: container-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      - name: Initialize Packer Plugins
        run: |
          packer init ./webapp-ami.pkr.hcl

      - name: Run Packer Fmt
        run: |
          packer fmt -check ./webapp-ami.pkr.hcl

      - name: Run Packer Validate
        run: |
          packer validate ./webapp-ami.pkr.hcl
