name: Packer CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      # Step to run `packer fmt` to ensure formatting
      - name: Run Packer Fmt
        run: |
          packer fmt -check ./webapp-ami.pkr.hcl
        continue-on-error: false

      # Step to run `packer validate` to ensure template is valid
      - name: Run Packer Validate
        run: |
          packer validate ./webapp-ami.pkr.hcl
        continue-on-error: false
