name: Build Packer Custom Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Create a zip file for the application
      - name: Create Application Zip
        run: |
          zip -r application.zip . -x "*.git*" "node_modules/*" # Exclude unnecessary files

      # Upload the built zip file as an artifact (optional but useful for debugging)
      - name: Upload Application Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-artifact
          path: ./application.zip

      # Download the application artifact for use in Packer (if needed)
      - name: Download Application Artifact
        uses: actions/download-artifact@v3
        with:
          name: application-artifact
          path: ./artifact-dir

      # Configure AWS credentials using the GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      # Install Packer
      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      # Run packer build to create the custom AMI
      - name: Build Custom Packer Image
        run: |
          packer build ./webapp-ami.pkr.hcl
