name: Build and Deploy Application

on:
  push: # Trigger on push to branches, not on pull_request
    branches:
      - main
      - dev # Only build custom image when a pull request is merged into main or dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # - name: Run Integration Tests
      #   run: npm test

      - name: Build Application Artifact
        run: |
          npm run build
          zip -r application.zip .

      - name: Check contents of application.zip (file names only)
        run: |
          unzip -l application.zip | awk '{print $4}' | tail -n +4 | head -n -2

      - name: Verify Artifact
        run: |
          if [ ! -f ./application.zip ]; then
            echo "Error: application.zip not found!"
            exit 1
          fi

      - name: List Directory Contents
        run: ls -la

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      - name: Create Packer variables file
        run: |
          echo 'artifact_path = "application.zip"' > variables.pkrvars.hcl

      - name: Build Custom Packer Image
        run: |
          packer init .
          packer build -var-file=variables.pkrvars.hcl ./webapp-ami.pkr.hcl

      - name: Modify AMI Launch Permissions
        run: |
          AMI_ID=$(packer output -machine-readable | grep 'artifact,0,id' | cut -d, -f6)
          aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "Add=[{UserId=${{ secrets.DEMO_ACCOUNT_ID }}}]"
