name: Build and Deploy Application

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Integration Tests
        run: npm test

      - name: Build Application Artifact
        run: |
          npm run build
          zip -r application.zip .

      - name: Verify Artifact
        run: |
          if [ ! -f ./application.zip ]; then
            echo "Error: application.zip not found!"
            exit 1
          fi

      - name: List Directory Contents
        run: ls -la

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      - name: Build Custom Packer Image
        run: packer build ./webapp-ami.pkr.hcl
