name: Build and Deploy Custom Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (or other build environment, e.g., Java, Maven)
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust according to your application

      - name: Install dependencies
        run: npm install # Adjust according to your application, e.g., `mvn install`

      - name: Run integration tests
        run: npm test # Adjust according to your testing framework

      # Build application artifact, adjust according to your application's build process (e.g., for Java, use `mvn package`)
      - name: Build application artifact
        run: |
          npm run build # Adjust according to your application build command
          zip -r app.zip . # Zip your build output to app.zip (if needed)

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: app.zip # Replace this with your actual artifact name (e.g., `.jar`, `.war`, `.zip`)

  packer-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: app-artifact

      # Configure AWS credentials using the GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      # Initialize Packer plugins
      - name: Initialize Packer Plugins
        run: |
          packer init ./webapp-ami.pkr.hcl

      # Build Packer Image
      - name: Build Custom Packer Image
        run: |
          packer build -var "artifact=app.zip" ./webapp-ami.pkr.hcl
