name: Build Packer Custom Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # You can adjust this version based on your project requirements

      - name: Install dependencies
        run: npm install

      - name: Build Application Artifact
        run: |
          zip -r application.zip .  # This will generate a zip file of the application in the current directory
          mkdir -p artifact-dir
          mv application.zip artifact-dir/

      - name: Check if zip file exists
        run: |
          if [ ! -f ./artifact-dir/application.zip ]; then
            echo "Zip file not found!"
            exit 1
          fi

      # Continue with Packer Build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      - name: Build Custom Packer Image
        run: |
          packer build ./webapp-ami.pkr.hcl
