name: Build Packer Custom Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Application Zip
        run: |
          mkdir -p artifact-dir
          zip -r artifact-dir/application.zip . -x "*.git*" "node_modules/*" # Create a zip excluding unnecessary files

      # Configure AWS credentials using the GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      # Install Packer
      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      # Initialize Packer plugins
      - name: Initialize Packer Plugins
        run: |
          packer init ./webapp-ami.pkr.hcl

      # Run Packer validate
      - name: Validate Packer Template
        run: |
          packer validate ./webapp-ami.pkr.hcl

      # Run packer build to create the custom AMI
      - name: Build Custom Packer Image
        run: |
          packer build ./webapp-ami.pkr.hcl
