name: Packer CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      # Step to initialize Packer plugins
      - name: Initialize Packer Plugins
        run: |
          packer init ./webapp-ami.pkr.hcl

      # Step to run `packer fmt` to ensure formatting
      - name: Run Packer Fmt
        run: |
          packer fmt -check ./webapp-ami.pkr.hcl

          - name: Install dependencies
          run: npm install

      - name: Run Integration Tests
        run: npm test

      - name: Build Application Artifact
        run: |
          npm run build
          zip -r application.zip .

      - name: Verify Artifact
        run: |
          if [ ! -f ./application.zip ]; then
            echo "Error: application.zip not found!"
            exit 1
          fi

      - name: List Directory Contents
        run: ls -la

      # Step to run `packer validate` to ensure template is valid
      - name: Run Packer Validate
        run: |
          packer validate ./webapp-ami.pkr.hcl
